#-------------------------------
# General Site Settings
baseURL = "https://blog.hecmisio.com"
languageCode = "en-US"
title = "HecMisio's Blog"

#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 9


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3

  [[menu.main]]
    identifier = "vlogs"
    name = "Vlogs"
    url = "/vlogs"
    weight = 4


[params]
  logo = "/images/logo.svg" # You can add own logo. For example "/images/logo.png".
  description = "HecMisio"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "HecMisio"
    author__bio = "Here I publish my thoughts on development, economics, psychology, life and so on."
    author__avatar = "/images/avatar.jpg"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Hey, I’m HecMisio"
    hero__description = "A software engineer(usually be a gopher)."
    hero__context = "Here I publish my thoughts on development, economics, psychology, life and so on."
    hero__image = "/images/hero.jpg"

  # Newsletter
  # [params.mailchimp]
  #   mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  #   mailchimp__input__text = "Subscribe here"
  #   mailchimp__button__text = "Subscribe"


  #-------------------------------
  # Gallery Footer Section
  # [params.gallery]
  #   gallery__title = "Gallery"
  #   gallery__columns = 3 # You can change the number of gallery columns

  # [[params.gallery_image]]
  #   image_alt = "Rest"
  #   image_url = "https://via.placeholder.com/800x600"

  # [[params.gallery_image]]
  #   image_alt = "Lifestyle"
  #   image_url = "https://via.placeholder.com/800x600"



  #-------------------------------
  # Contact Settings
  #[params.contact]
  #  email = "misiohec@gmail.com" # Add your email for contant form

    # NOTE
    # Menca comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  #[params.disqus]
  #  disqusShortname = "HecMisio" # Add your shortname for Disqus Comment. For example demo-menca


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.x]
    disable = true
  [privacy.youtube]
    disable = true

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'en'
    weight = 1
  [languages.zh]
    disabled = false
    languageCode = 'zh-cn'
    languageDirection = 'ltr'
    languageName = 'zh'
    weight = 2
    [languages.zh.menu]
      [[languages.zh.menu.main]]
        identifier = "home"
        name = "首页"
        url = "/zh"
        weight = 1
      [[languages.zh.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/zh/about"
        weight = 2
      [[languages.zh.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/zh/tags"
        weight = 3
      [[languages.zh.menu.main]]
        identifier = "vlogs"
        name = "Vlogs"
        url = "/zh/vlogs"
        weight = 4
    [languages.zh.params.hero]
      hero__title = "你好, 我是 HecMisio"
      hero__description = "一位软件开发工程师（通常是Gopher）"
      hero__context = "这里是我的博客，分享有关开发，经济学，心理学，生活......的想法"
      hero__image = "/images/hero.jpg"
    [languages.zh.params.author]
      author__name = "HecMisio"
      author__bio = "分享有关开发，经济学，心理学，生活......的想法"
      author__avatar = "/images/avatar.jpg"